### ISSUE TITLE
Different item counts between package and API

### ISSUE THREAD

**Issue by pkraker** [njahn82/ropenaire#15]
As reported by @chreman:

`roa_pubs(fp7 = "330731")` returns 67 publications

http://api.openaire.eu/search/publications?projectID=330731&funder=EC&format=xml shows me `<total>22</total>`

**Comment by sckott** [comment]
thx, will have a look

**Comment by sckott** [comment]
ah, sorry for the delay - there's simply many rows for any one match - 

do you prefer we return a single row per record?

if you use `format=xml` you do get back 22 records (22 `<result>` nodes)

**Comment by pkraker** [comment]
@chreman Can you please take a look?

**Comment by sckott** [comment]
Any thoughts on this @pkraker or @chreman ?
