### ISSUE TITLE
roa_datasets always returns 0 results for project_id and funder

### ISSUE THREAD

**Issue by pkraker** [njahn82/ropenaire#17]
Examples: 
http://api.openaire.eu/search/datasets?projectID=642954&funder=EC returns 5 datasets
`roa_datasets(project_id = "642954", funder = "EC")` returns 0 datasets

http://api.openaire.eu/search/datasets?projectID=312463&funder=EC returns 77 datasets
`roa_datasets(project_id = "312463", funder = "EC")` returns 0 datasets

**Comment by chreman** [comment]
I think this is related to the commit https://github.com/sckott/ropenaire/commit/42c205678a0adff1195c19639d4083de5d2573de which also needs to be implemented for roa_datasets.

**Comment by sckott** [comment]
right, open issue already https://github.com/njahn82/ropenaire/issues/16

**Comment by sckott** [comment]
@pkraker can you try this again after reinstalling - should be fixed now

**Comment by pkraker** [comment]
Works now as expected, thanks!

**Comment by sckott** [comment]
can you close @njahn82 ?
