### ISSUE TITLE
merge sckott/ropenaire here?

### ISSUE THREAD

**Issue by sckott** [njahn82/ropenaire#20]
@njahn82 okay to merge what we have in my version here for now?  and can continue any further changes on my version, and PR again, etc.

**Comment by njahn82** [comment]
Sure. However, I wonder if it makes more sense to transfer the repo to you because you intend to use it in production for Open Knowledge Maps?

**Comment by sckott** [comment]
Up to you really, your the maintainer/owner. Do you think you'll have time/interest to maintain it after my bout of work for Okmaps is done? Or are you not likely to maintain it?

**Comment by njahn82** [comment]
Well, I could maintain it after your work is done. Maybe merging back and forth is thus a good idea.

**Comment by sckott** [comment]
Okay, I'll send a PR then
