### ISSUE TITLE
Title search in roa_projects throws an error

### ISSUE THREAD

**Issue by pkraker** [njahn82/ropenaire#5]
Steps to reproduce:
1. Search for a title, e.g. `roa_projects(title="open", size=10)`

Example error message:
```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 10, 8
```

**Comment by sckott** [comment]
fixed in https://github.com/sckott/ropenaire/commit/2cf931a253ffa8d7f53e7fd3e0c794248eb6f0e8

**Comment by sckott** [comment]
@njahn82 can you close this? i don't have access to close

**Comment by njahn82** [comment]
Thank you for reporting and fixing it, will close it
